Feat: Add Email Send View
DeveloperAcademy-POSTECH/MC2-Team3-SSAK3 pull request #273
Opened 2022-10-30 03:21 UTC by pis3120

## 작업사항
-설정화면에서 "개발자에게 의견 남기기" 버튼 누르면 이메일 폼으로 넘어감
- 이메일 앱 미설치시, 앱스토어로 연결 

## 리뷰포인트

https://user-images.githubusercontent.com/40324511/198861044-546425a3-84d9-4d22-af75-9ad8b436cd9e.mp4

https://user-images.githubusercontent.com/40324511/198861048-15b37915-d62b-4fb7-a9f5-11fbe6c56a35.mp4

### 다음으로 진행될 작업

### 질문

### 기타

### References

2022-10-31 01:52 UTC, HoJongE requested changes
수고하셨씁니다! 몇 개만 수정하고 바로 머지하면 될 것 같아요~~

2022-10-31 01:52 UTC, HoJongE commented on Taxi/Taxi/Presenter/MyPage/EmailSendView.swift
> +class EmailHelper: NSObject {
더 이상 상속되지 않으면 final 을 붙여주세요!

2022-10-31 01:52 UTC, HoJongE commented on Taxi/Taxi/Presenter/MyPage/EmailSendView.swift
> +    static let shared = EmailHelper()
singleton 으로 하신 이유가 있나요? 그렇게 많이 사용되지 않는 인스턴스라서, 싱글톤을 굳이 사용하지 않아도 될 것 같아요

2022-10-31 01:52 UTC, HoJongE commented on Taxi/Taxi/Presenter/MyPage/EmailSendView.swift
> +import MessageUI
MessageUI 는 써드파티 라이브러리인가요? 아니면 애플에서 기본 지원해주나요?

2022-10-31 01:52 UTC, HoJongE commented on Taxi/Taxi/Presenter/MyPage/EmailSendView.swift
> +import Foundation
SwiftUI 에 아마 기본으로 Foundation 이 들어가있을거에요. 따라서 지워주시면 될 것 같아요

2022-10-31 01:52 UTC, HoJongE commented on Taxi/Taxi/Presenter/MyPage/LicenseView.swift
> +    var opensourceLicense2: some View {
이름에 2가 붙는 이유가 있나요??

2022-10-31 01:52 UTC, HoJongE commented on Taxi/Taxi/Presenter/MyPage/MyPageView.swift
> +    @State private var isAccountOff: Bool = false
새롭게 추가된 이 두 개의 프로퍼티는 뭘 위한 프로퍼티인가요? 밑에 보니까 사용하는 곳이 없는 것 같아서요!

2022-11-01 03:35 UTC, pis3120 commented on Taxi/Taxi/Presenter/MyPage/MyPageView.swift
> +    @State private var isAccountOff: Bool = false
이 부분은 다른분이 추가하신거 같아요~!

2022-11-01 03:35 UTC, pis3120 commented on Taxi/Taxi/Presenter/MyPage/LicenseView.swift
> +    var opensourceLicense2: some View {
금일 수정할 예정입니다!

2022-11-01 03:35 UTC, pis3120 commented on Taxi/Taxi/Presenter/MyPage/EmailSendView.swift
> +import Foundation
디테일한 리뷰 감사합니다!

2022-11-01 09:19 UTC, pis3120 commented on Taxi/Taxi/Presenter/MyPage/EmailSendView.swift
> +class EmailHelper: NSObject {
수정하였습니다~!

2022-11-01 09:20 UTC, pis3120 commented on Taxi/Taxi/Presenter/MyPage/EmailSendView.swift
> +import MessageUI
애플 기본 지원 라이브러리입니다~!

2022-11-01 09:34 UTC, pis3120 commented on Taxi/Taxi/Presenter/MyPage/EmailSendView.swift
> +    static let shared = EmailHelper()
해당 부분 singleton으로 shared 주지 않으면, 아래 extenstion에서  UIApplication.shared 등을 이용할때 접근이 안되서 썼습니다!

2022-11-01 09:34 UTC, pis3120 commented on Taxi/Taxi/Presenter/MyPage/MyPageView.swift
> +    @State private var isAccountOff: Bool = false
아아 헷갈렸네요!

2022-11-01 09:38 UTC, pis3120 commented on Taxi/Taxi/Presenter/MyPage/MyPageView.swift
> +    @State private var isAccountOff: Bool = false
테스트할때 넣었던 코드있데 삭제 하였습니다~!

2022-11-01 09:39 UTC, pis3120 commented on Taxi/Taxi/Presenter/MyPage/LicenseView.swift
> +    var opensourceLicense2: some View {
테스트 할때, 넣었는데, 수정완료하였습니다~~!

2022-11-06 09:51 UTC, HoJongE approved these changes
수고하셨습니다!

2022-11-06 15:24 UTC, merged