Feature/#22 custom calendar
DeveloperAcademy-POSTECH/MC2-Team3-SSAK3 pull request #43
Opened 2022-06-10 12:04 UTC by SH0123

## 작업사항
커스텀 캘린더 제작
- 오늘 기준 한달만 선택할 수 있도록
- 택시팟이 있는 날에는 표시가 되도록

## 리뷰포인트
전체적인 코드 스타일 디테일하게 리뷰 부탁드립니다 ~ 개선하겠습니다

### 구현 화면
![ezgif com-gif-maker-7](https://user-images.githubusercontent.com/26588989/173060150-185c3e93-e7f9-41d0-87a6-4e24f273cc50.gif)

### 다음 작업 내용
다른 view와 연동시 state 값들을 부모 view에서 선언해주고, 하위 뷰인 custom calendar에서는 binding으로 변경 필요
이에 따른 init 함수 작성 필요

### 기타

### References

2022-06-10 12:07 UTC, SH0123 commented
[Help]
<img width="500" alt="스크린샷 2022-06-10 오후 9 06 36" src="https://user-images.githubusercontent.com/26588989/173060962-effcb07f-9bc4-4abb-ac2c-6ebebf753886.png">

private은 이런 상황에서는 사용할 수 없는것일까요?

2022-06-10 12:46 UTC, HoJongPARK commented
> [Help] <img alt="스크린샷 2022-06-10 오후 9 06 36" width="500" src="https://user-images.githubusercontent.com/26588989/173060962-effcb07f-9bc4-4abb-ac2c-6ebebf753886.png">
> 
> private은 이런 상황에서는 사용할 수 없는것일까요?

해당 변수는 메소드 내 지역변수입니다. 지역변수는 어차피 외부에서 접근이 아예 불가능하기 때문에 접근 지정자 같은건 필요없습니다

2022-06-10 12:57 UTC, HoJongPARK requested changes
변경사항 적용 부탁드립니다

2022-06-10 12:57 UTC, HoJongPARK commented on Taxi/Taxi/Domain/Model/TaxiParty.swift
> +func mockData() -> [TaxiParty] {
Mock Data 를 정의하는 다양한 방법이 있습니다.

단순히 이렇게 전역 메소드를 정의해버린다면 release 버전에선 사용하지도 않을 코드를 불필요하게 포함하는 셈이 됩니다 

#if DEBUG 구문을 활용해 디버그 용에서만 사용할 Mock data 를 만들어보세요. 또한 TaxiParty 모델에 추가하지말고 Mock Data 를 관리하는 새로운 파일을 생성해서 작성해보세요

2022-06-10 12:57 UTC, HoJongPARK commented on Taxi/Taxi/Extension/IntExtension.swift
> +    }
변환에 실패하는 경우를 생각한다면 그냥 throws 로 에러처리를 강제하거나 nil 타입을 반환하는게 나아보이네요. 현재 Date 를 반환하는 것은 에러는 나지 않지만 추후 앱이 이상하게 동작하는 원인이 될 수 있습니다

2022-06-10 12:57 UTC, HoJongPARK commented on Taxi/Taxi/Extension/IntExtension.swift
> +}
이 부분도 마찬가지입니다

2022-06-10 12:57 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/CalendarView.swift
> +        var navigation: some View {
계산 프로퍼티 안에 계산 프로퍼티를 중첩하는게 어떤 장점이 있나요?? 순수하게 궁금해서 물어보는겁니다

2022-06-10 13:02 UTC, SH0123 commented on Taxi/Taxi/Domain/Model/TaxiParty.swift
> +func mockData() -> [TaxiParty] {
공부후 반영하여 commit 주소 남기겠습니다 ~
감사합니다. 하나 배워갑니다 ㅎㅎ

2022-06-10 13:07 UTC, SH0123 commented on Taxi/Taxi/Extension/IntExtension.swift
> +}
공부후 반영하여 commit 주소 남기겠습니다 ~
아 그리고 해당 코드는 파이어베이스에서 받아온 TaxiParty 객체의 meetingDate(Int)를 해당 String으로 바꿔주는 int extension의 function이니 사용하시면 됩니다.
@YoonyoungL @pis3120

2022-06-10 13:09 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +        var navigation: some View {
이건 header 안에 들어가야할 요소가 2가지여서 파악하기 편하게 하기 위해 이렇게 구성했습니다.
또 다른 좋은 방법이 있거나 이 방법이 좋지 않다면 다른 방법 추천 부탁드립니다

2022-06-10 13:09 UTC, SH0123 commented on Taxi/Taxi/Extension/IntExtension.swift
> +    }
공부후 반영하여 commit 주소 남기겠습니다 ~
변환에 실패하는 경우가 앱에 문제를 발생시키는 경우에는 다 에러처리를 해버리는게 좋을까요? 
이에 대해 추후 고민하고 배워보고싶습니다 ~

2022-06-11 08:03 UTC, Chaeho-Min reviewed
역시 달력 깎는 장인... 이 코드 보고 달력 만드는 법 배우겠습니다!

2022-06-11 08:03 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CalendarView.swift
> +                            return
옵셔널 체크에 사용한 taxiParty가 한 번도 쓰이지 않았다는 경고가 떠서 fix를 누르면 아래와 같이 바뀌는데 뭐가 더 좋은 방법인가요?
```swift
guard taxiParties.first(where: {party in
    data.date.isSameDay(party.meetingDate.intToDate())
}) != nil else {
    action()
    return
}
```

2022-06-11 08:12 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CalendarView.swift
> +            .padding(.bottom, 20)
dayOfWeek과의 간격을 위해 bottom padding 값을 준 것이라면, VStack의 spacing을 사용해보는 것은 어떨까요?
padding으로 간격을 조정하는 것보다 가독성이 좋다고 생각합니다.

2022-06-11 10:22 UTC, HoJongPARK requested changes

2022-06-11 10:22 UTC, HoJongPARK commented on Taxi/Taxi/MockData/TaxiPartyMockData.swift
> +    var mockData: [TaxiParty] {
어차피 DEBUG 빌드에서만 사용될텐데 static 으로 선언해서 굳이 인스턴스를 생성하지 않고도 사용하게 하면 어떨까요

2022-06-11 10:22 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/CalendarView.swift
> +            let days = ["일", "월", "화", "수", "목", "금", "토"]
계산 프로퍼티 안에서 배열을 생성해버리면 뷰가 업데이트될 때마다 배열을 생성하므로 차라리 struct 프로퍼티로 선언한다음 사용하는게 낫습니다

2022-06-11 10:22 UTC, HoJongPARK commented on Taxi/Taxi/Extension/IntExtension.swift
> +    }
제가 봤을 때 Int 타입을 Date 타입으로 변환하는 함수를 Int extension 에 작성하는 것은 별로 좋지 못한 방법인 것 같습니다.

일단 모든 Int 가 Date 로 변환될 수 있는 것도 아닌데, 모든 Int 에서 접근할 수 있는 함수를 선언하는게 이상해보이며 만약 이런식으로 작성할 거면 앞서 말한 것처럼 변환실패를 가정해 에러 처리를 강제하도록 하던가 nil 타입으로 반환하는게 좋아보입니다.

하지만 제일 좋은 방법은 차라리 Converter class 를 하나 만들어서 해당 모델에서 Int 를 Date 로 변환하는게 제일 좋아보이네요

2022-06-11 10:22 UTC, HoJongPARK commented on Taxi/Taxi/Extension/IntExtension.swift
> +    }
만약 21억이라는 정수를 개발자가 사용할 때, intToDate 라는 함수가 자동완성에 뜬다면 당황하겠죠

2022-06-11 10:22 UTC, HoJongPARK commented on Taxi/Taxi/Extension/IntExtension.swift
> +}
함수의 네이밍이 조금 이상한 것 같습니다. 일단 intToString 이름의 뜻이 Int 를 문자열 타입으로 바꾼다. 이런 뜻인데 Date 형태의 Int 를 사람이 읽을 수 있는 String 타입으로 변환한다는 의미가 전달이 잘 안되는 것 같습니다. 또한 Int Extension 에 정의되기에는 부적절한 함수인 것 같습니다

2022-06-11 13:25 UTC, Chaeho-Min commented on Taxi/Taxi/MockData/TaxiPartyMockData.swift
> +        TaxiParty(id: "6", departureCode: 1, destinationCode: 0, meetingDate: 20220621, meetingTime: 1931, maxPersonNumber: 3, members: ["연승", "효상", "인서"], isClosed: false)
TaxiParty의 members 배열에는 각 User의 id가 들어가야 하는 부분입니다!
더미데이터라 큰 상관은 없지만 혹시나 더미데이터 사용하다가 혼란스러워 할 분들이 계실까봐 말씀드립니다.(사실 제가 이거 보고 따라서 더미데이터 생성했다가 고쳤습니다...)

2022-06-12 07:38 UTC, SH0123 commented on Taxi/Taxi/Extension/IntExtension.swift
> +    }
감사합니다. extension을 사용하는것이 나름 괜찮은 방법이라는 생각만 갖고 사용했었는데, 예시를 통해서 자세히 설명해주신 덕분에 이런 상황에서는 오히려 혼란과 오류를 야기할 수 있다는 것을 깨닫게 되었습니다.
함수 명칭과 선언 위치에 대한 고민을 해보고 다시 작성한 뒤 커밋 주소 남기도록 하겠습니다 ~

2022-06-12 07:40 UTC, SH0123 commented on Taxi/Taxi/Extension/IntExtension.swift
> +}
감사합니다. 작성하면서도 네이밍이 애매해서 고민이 많았는데 어물쩡 넘어가려는 것을 잘 짚어주신 덕분에 꼼꼼히 하고 넘어가는 습관을 잡을 수 있을 것 같습니다
반영후에 커밋 주소 남기겠습니다.

2022-06-12 07:41 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +        }
이 부분은 다른 분의 코드를 살짝 참고했는데, 아보처럼 투철하게 생각하지 못하고 마냥 참고만 한 것 같아 반성하게 됩니다.
반영하여 커밋 메세지 남기도록 하겠습니다.
감사합니다 ~

2022-06-12 07:41 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +                            return
도움을 주세요 ~~!!

2022-06-12 07:43 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +        .frame(width: UIScreen.main.bounds.width * 0.85, height: UIScreen.main.bounds.height * 0.4, alignment: .top)
맞아요. 사실 높이를 설정하지 않았을 때 헤더가 자꾸 움직이는 이슈가 발생하여 이렇게라도 해버리고 넘어가자는 못된 마음으로 어물쩡 하고 넘어가려 했는데, 아보 덕분에 다시 한 번 꼼곰하게 체크하고 코드를 작성해볼 수 있게 되었습니다.
고민하고 반영하여 주소 남겨놓겠습니다 ~

2022-06-12 07:44 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +            .padding(.bottom, 20)
반영해보겠습니다 ㅎㅎ 꼼꼼한 리뷰 감사합니다

2022-06-12 07:45 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/CalendarView.swift
> +                            return
말 그대로 guard 문에 옵셔널 바인딩을 사용한다는 것은 옵셔널 바인딩으로 선언된 상수나 변수를 guard 문 통과 시 사용하겠다는 의미인데, 해당 변수나 상수를 guard 문 아래 코드에서 사용하지 않으면 해당 워닝이 뜨게 됩니다. 

즉 옵셔널 바인딩으로 선언한 상수나 변수를 사용하지 않을 때는, 옵셔널 바인딩말고 단순 nil 체크 하는게 좋지 않을까요?

2022-06-12 07:46 UTC, SH0123 commented on Taxi/Taxi/MockData/TaxiPartyMockData.swift
> +    var mockData: [TaxiParty] {
오 좋은 방법인 것 같습니다.
인스턴스를 생성하게 되면 메모리 부분에서 필요없는 낭비가 생기게 되나요? 어떤점에서 static이 좋은지 설명 부탁드립니다 ~

2022-06-12 07:47 UTC, SH0123 commented on Taxi/Taxi/MockData/TaxiPartyMockData.swift
> +        TaxiParty(id: "6", departureCode: 1, destinationCode: 0, meetingDate: 20220621, meetingTime: 1931, maxPersonNumber: 3, members: ["연승", "효상", "인서"], isClosed: false)
앗 ㅋㅋㅋㅋㅋ 제가 실수했네요 ㅠㅠ 제 더미데이터도 수정하겠습니다
저에게 중요하지 않은 데이터 부분이라 신경쓰지 않고 사용했었습니다.
다음부터는 모델에 대한 좀 더 깊은 이해도를 바탕으로 코드를 작성해보겠습니다 ~

2022-06-12 07:47 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CalendarView.swift
> +        .frame(width: UIScreen.main.bounds.width * 0.85, height: UIScreen.main.bounds.height * 0.4, alignment: .top)
달력이 5줄일 때도 있고 6줄일 때도 있어서 헤더가 움직이는 것이라면, 5줄일 때는 똑같은 높이의 보이지 않는 한 줄을 추가하는 것은 어떨까요?

2022-06-12 07:50 UTC, HoJongPARK commented on Taxi/Taxi/MockData/TaxiPartyMockData.swift
> +    var mockData: [TaxiParty] {
솔직히 메모리 부분은 제가 정확하진 않지만, 어차피 릴리즈 버전에서 제외될 코드면 별로 상관없지 않을까요? 

단순히 목데이터의 경우 개발자가 편리하게 사용할 수 있도록 코드를 작성하는게 좋을 것 같은데, 

인스턴스를 생성해서 목데이터를 사용하게 할 것이냐, MockData 타입 자체에서 바로 목데이터에 접근 가능하게 할 것이냐.

이 부분은 무작정 바꾸는 것보단 팀 규칙으로 정하는게 나을 것 같기도 하네요.

2022-06-12 07:51 UTC, HoJongPARK commented on Taxi/Taxi/MockData/TaxiPartyMockData.swift
> +    var mockData: [TaxiParty] {
언제 한 번 MockData 클래스에서 필요한 Mock data 반환 코드를 전부 작성한다음, 팀끼리 공유해서 불필요한 mock 데이터 생성 코드를 줄이는 방향으로 진행해야겠네요.

2022-06-12 13:25 UTC, SH0123 commented on Taxi/Taxi/Extension/IntExtension.swift
> +    }
85e1d4582dcdec283a128212d00ba1e29453cb1d
반영 완료하였으나 함수 명칭에 관해서는 아직 고민이 많습니다.
그리고 class 내부에 static으로 함수를 선언해서 인스턴스 생성 없이 사용할 수 있도록 할지, 인스턴스를 생성하고 사용하도록 할지 고민을 하다가, 필요할 때에만 객체를 생성해서 사용하는 것이 메모리 측면에서 더 나을 것 같아 인스턴스 함수로 만들었습니다.
해당 파일을 어느 위치에 놓아야 할 지 몰라 domain 폴더 내에 위치 했습니다.

피드백 부탁드립니다 ~

2022-06-12 13:25 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +        }
85e1d4582dcdec283a128212d00ba1e29453cb1d
반영 완료했습니다 ~ 
padding(.vertical, 20) 부분도 가독성을 위해 VStack(spacing: 20)으로 반영 완료했습니다 ~

2022-06-12 13:26 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +        .frame(width: UIScreen.main.bounds.width * 0.85, height: UIScreen.main.bounds.height * 0.4, alignment: .top)
85e1d4582dcdec283a128212d00ba1e29453cb1d
해당 부분과 관련하여 몇째줄의 몇번칸까지 달력 날짜가 채워졌는지 확인하고, 5줄이라면 6번째 줄 까지 임의의 데이터를 넣을 수 있도록 함수를 만들었습니다 ~

2022-06-12 13:27 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +                            return
85e1d4582dcdec283a128212d00ba1e29453cb1d
감사합니다 ~ 반영 완료했습니다

2022-06-12 13:44 UTC, Chaeho-Min reviewed
엄청난 수정...!! 고생하셨습니다!
근데 정말 죄송하지만 달력에서 하나 궁금한게 있는데... 선택할 수 있는 날짜가 없는 월로는 넘어갈 수 있어야 할 필요가 있나요?

2022-06-12 13:44 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CalendarView.swift
> +        .frame(maxWidth: .infinity)
이미 내부에 dayOfWeek이나 dayCell이 .infinity 속성이기 때문에 이 전체 VStack도 최대 너비를 차지하게 됩니다.
따라서 여기서 또 .infinity를 줄 필요는 없습니다.
전체 컨텐츠에는 좌우 마진값을 주는게 좋습니다.
```suggestion
        .padding(.horizontal)
```

2022-06-12 13:44 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CalendarView.swift
> +        return HStack {
위에 navigation에서 return을 안 썼으니까 여기서도 안 쓰는게 좋을 것 같습니다!
```suggestion
        HStack {
```

2022-06-12 13:44 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CalendarView.swift
> +                            .frame(maxWidth: .infinity, maxHeight: .infinity)
Circle과 같은 Shape는 이미 .infinity 속성을 갖고 있습니다. 따라서 여기서 프레임은 사용하지 않아도 됩니다.

```suggestion

```

2022-06-12 14:02 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +        .frame(maxWidth: .infinity)
이 부분에서 궁금한게 있는데, 달력을 컴포넌트용으로 만들었으니 사용하는 사람들이 padding()을 적절하게 사용하면 된다고 생각하여 padding은 아직 넣어주지 않은 상태입니다.
컴포넌트 단계에서 padding을 주는게 좋을까요? 아니면 사용하는 사람이 padding을 적절히 주는게 좋을까요?

2022-06-12 14:03 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +        .frame(maxWidth: .infinity)
못넘어가게... 할까요... 괴롭히지 마세요 ㅠㅠㅠ 흑흑 내일 수정해보겠습니다
사실 인터파크 같은 앱에서도 못넘어가게 하기는하더라구요 하핳

2022-06-12 14:04 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +                            .frame(maxWidth: .infinity, maxHeight: .infinity)
오 그런건 어떻게 알게되는건지 알게된 경로 알려주세요 ㅎㅎ 저도 레이아웃 관련해서 잘 알고싶어요 ~ 감사합니다 ~

2022-06-12 14:13 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CalendarView.swift
> +        .frame(maxWidth: .infinity)
> 이 부분에서 궁금한게 있는데, 달력을 컴포넌트용으로 만들었으니 사용하는 사람들이 padding()을 적절하게 사용하면 된다고 생각하여 padding은 아직 넣어주지 않은 상태입니다.
> 컴포넌트 단계에서 padding을 주는게 좋을까요? 아니면 사용하는 사람이 padding을 적절히 주는게 좋을까요?

이건 저도 들어보니까 고민이 되네요 ㅎㅎ
컴포넌트에 있는걸 뺄 수는 없지만 없는걸 넣을 수는 있으니가 쓰지 않는게 더 좋을수도?

2022-06-12 14:13 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CalendarView.swift
> +        .frame(maxWidth: .infinity)
> 못넘어가게... 할까요... 괴롭히지 마세요 ㅠㅠㅠ 흑흑 내일 수정해보겠습니다
> 사실 인터파크 같은 앱에서도 못넘어가게 하기는하더라구요 하핳

😈

2022-06-12 14:15 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CalendarView.swift
> +                            .frame(maxWidth: .infinity, maxHeight: .infinity)
> 오 그런건 어떻게 알게되는건지 알게된 경로 알려주세요 ㅎㅎ 저도 레이아웃 관련해서 잘 알고싶어요 ~ 감사합니다 ~

음... 경험으로?
처음에 스유를 배울 때 Rectangle이 차지할 수 있는 최대 크기를 차지한다고 배웠고, 나중에 써보니까 RoundedRectangle, Circle 이런 것들도 다 똑같더라고요. 그래서 Shape은 다 그렇구나~ 하고 넘어간 것 같네요.

2022-06-13 03:22 UTC, unnnyong commented on Taxi/Taxi/Domain/DateTypeConverter.swift
> +}
```swift
extension Date {
    static func convertToKoreanDateFormat(from date: Int) -> String {
        let dateStr = String(intDate)
         let formatter = DateFormatter()
         formatter.dateFormat = "yyyyMMdd"
         formatter.locale = Locale(identifier: "ko_KR")
         formatter.timeZone = TimeZone(abbreviation: "KST")

         let date = formatter.date(from: dateStr) ?? Date()
         return "\(date.month)월 \(date.day)일"
    }
}
```

```swift
// 사용할 때,
Date.convertToKoreanDateFormat(from: 20220613)
```

`Date` class의 Extension 으로 하면 어떤가용 ? 불러서 쓸 때도 조금 더 심플해 질 수 있을 것 같아요 ~

---


Taxi/Taxi/Extension/DateExtension.swift 와도 중복되는 듯해서,,, 둘 사이의  교통정리가 필요해보이네요

2022-06-13 03:23 UTC, unnnyong commented on Taxi/Taxi/MockData/TaxiPartyMockData.swift
> +#if DEBUG
😻 😻 😻 😻 😻 😻

2022-06-13 03:23 UTC, unnnyong commented on Taxi/Taxi/Extension/DateExtension.swift
> +        return self.dateComponents.day ?? -1
-1 이 어떤 의미인가용 ? 👀

2022-06-13 03:24 UTC, unnnyong commented on Taxi/Taxi/Extension/DateExtension.swift
> +    }
```suggestion
    var isToday: Bool {
        let calendar = Calendar.current
        return calendar.isDate(self, inSameDayAs: Date())
    }
```

computed property로도 될 수 있을 것 같아요 ~~
`class Calendar`의 extension으로 되는게 적절해보이기도 하네요

2022-06-13 03:24 UTC, unnnyong commented on Taxi/Taxi/Extension/DateExtension.swift
> +    func isOutOfMonth() -> Bool {
[이 코멘트](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/pull/43/files#r895298527)와 비슷할 듯 합니다 ~

2022-06-13 03:26 UTC, unnnyong commented on Taxi/Taxi/Presenter/CalendarView.swift
> +    let days = ["일", "월", "화", "수", "목", "금", "토"]
```suggestion
    private let days = ["일", "월", "화", "수", "목", "금", "토"]
```

이 친구도 접근제한자 설정 가능해보여욥

2022-06-13 03:27 UTC, unnnyong commented on Taxi/Taxi/Presenter/CalendarView.swift
> +    init(calendarType: CalendarType = .modalFilter, action: @escaping () -> Void) {
action을 Swift의 async/await 를 활용해보는건 어떤가요 ?

2022-06-13 03:33 UTC, unnnyong commented on Taxi/Taxi/Presenter/CalendarView.swift
> +    }
이 부분은 View와 관련된 되었다기보다는, Calendar의 데이터 핸들링에 가까워보여요 ~
Calendar 의 extension이나 별도의 ViewModel로 선언하면 어떨까요 ?

2022-06-13 03:36 UTC, unnnyong commented on Taxi/Taxi/Presenter/CalendarView.swift
> +    private func dayCell(_ value: DayContainer) -> some View {
```suggestion
    private func makeDayCell(_ value: DayContainer) -> some View {
```

메소드 이름으ㅣ 시작은 동사로 하는걸 추천드립니다 ✨

2022-06-13 03:38 UTC, unnnyong commented on Taxi/Taxi/Presenter/CalendarView.swift
> +enum CalendarType {
코드를 사용하기전에 명명(작성)되어있으면 순서대로 읽기 쉬울 것 같아요 ~
이 enum을 swift file의 가장 상단으로 이동시키면 [사용되는 곳](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/pull/43/files#diff-fd789d894734e16cd155d4f213166002f4699f84d0d0ba8172f085f728f55358R17)이 나타났을 때, 아 위에서 작성한게 여기서 사용되구나 ~~~ 라고 알기 쉬울 것 같습니다. : )

2022-06-13 03:38 UTC, unnnyong commented on Taxi/Taxi/Presenter/CalendarView.swift
> +            if value.day != 0 {
여기를 guard로 하면 전체적으로 indent가 줄어들어서 읽기 쉬워질 것 같아요 : )

2022-06-13 06:18 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CalendarView.swift
> +    private func dayCell(_ value: DayContainer) -> some View {
저는 개인적으로 얘는 뷰라서 동사가 아닌게 더 어울린다고 생각하는데 혹시 동사를 추천하는 이유가 있으실까요??

```swift
LazyVGrid {
    ForEach(...) { data in
        dayCell(data)
            .background(...)
    }
}
```

```swift
LazyVGrid {
    ForEach(...) { data in
        makeDayCell(data)
            .background(...)
    }
}
```

2022-06-13 06:18 UTC, closed without merging

2022-06-13 11:01 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/CalendarView.swift
> +            if value.day != 0 {
조건문이 거짓일 때 반환하려던 뷰를 똑같이 return 해주면 됩니다

2022-06-13 11:17 UTC, SH0123 commented on Taxi/Taxi/Extension/DateExtension.swift
> +        return self.dateComponents.day ?? -1
해당 부분 리뷰해주신 내용을 바탕으로 수정해보고 있는 중인데, 혼란스러운 부분이 생겨서 대면 질문 요청드립니당..
```swift
var day: Int? {
    return self.dateComponents.day
}
```
위와 같이 nil 값이 아닌 애매한 값을 리턴하는 것 보다 optional을 리턴하는게 좋을 것 같다는 피드백을 바탕으로 코드를 수정해봤습니다.
이 다음 단계에서 막히는 부분이 생겼습니다.

https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/blob/feature/%2361_calendar_hifi/Taxi/Taxi/Presenter/CalendarView.swift#L134-L136 
```swift
var thisMonthDates = current.getMonthDates().map { date in
            DayContainer(day: date.day, date: date, monthType: checkMonthType(date))
        }
```
해당 코드가 guard let 옵셔널 바인딩을 통해 아래와 같이 변경되는 것 같습니다.
```swift
var thisMonthDates = current.monthDates.map { date -> DayContainer in
            guard let day = date.day else { return DayContainer(day: 0, date: date, monthType: .unparticipable) }
            return DayContainer(day: day, date: date, monthType: checkMonthType(date))
        }

```

질문
optional binidng을 해주기 때문에 guard let의 else 구문에서 nil인 경우 반환하는 값을 넣어줘야하는데 어떤 값을 넣어줘야 하는지 알고싶습니다. 아무 값을 반환하게 된다면 결국 임의의 값을 return한다는 점에서 위의 코드 
```swift
return self.dateComponents.day ?? -1
```
과 다른 부분이 없는건 아닌지 궁금합니당

2022-06-13 11:38 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +            if value.day != 0 {
만약에 거짓일 때는 아무값도 반환하지 않으려 했다면 어떻게 하면 되나요?

2022-06-13 11:41 UTC, SH0123 commented on Taxi/Taxi/Domain/DateTypeConverter.swift
> +}
date extension에서 사용할 수 있는 방법이 없을지 고민하다가 좋은 결론을 내리지 못했는데, 좋은 피드백 감사합니다 ~ 반영하여 댓글로 남기겠습니다 ~

2022-06-13 13:12 UTC, SH0123 commented on Taxi/Taxi/Extension/DateExtension.swift
> +        return self.dateComponents.day ?? -1
21a1f4fb0bb31a36e708f2da98acdafc35f5f5e0 반영 하였지만 위의 내용들과 관련하여 궁금증이 해소되지 않아 대면 질문 드리고싶습니다 ㅎㅎ
1. guard let 혹은 guard를 사용할 때 else에는 어떤 값을 return하면 좋은지
2. viewbuilder에서는 guard문을 사용할 때 어떤 값을 return해야할 지

2022-06-13 13:13 UTC, SH0123 commented on Taxi/Taxi/Extension/DateExtension.swift
> +    }
21a1f4fb0bb31a36e708f2da98acdafc35f5f5e0 반영 완료하였습니다.
인자를 받지 않는 함수는 computed property로 대체될 수 있으며, 동사형의 명명법은 피하는게 좋다!

2022-06-13 13:15 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +    init(calendarType: CalendarType = .modalFilter, action: @escaping () -> Void) {
이 부분은 잘 모르겠습니다...
action은 비동기로 처리하지 않는 함수 라는 생각을 해보는데 async/ await을 어떤 방식으로 활용하면 좋을지 대면 질문 드리고 싶습니다 ㅎㅎ

2022-06-13 13:17 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +enum CalendarType {
21a1f4fb0bb31a36e708f2da98acdafc35f5f5e0 반영 완료했습니다.
따로 파일을 만들어서 작성해도 된다! 
상단에 이동시키지 않는 경우 맨 밑에까지 내려와서 읽고 다시 확인하기 위해 올라가는 번거로움이 생길 수 있다!

2022-06-13 13:18 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +            if value.day != 0 {
21a1f4fb0bb31a36e708f2da98acdafc35f5f5e0 반영 완료하였으나 아직 혼란스러운 부분이 있습니다 ㅠ
첫번째 리뷰해주신 부분과 맥락이 같은 것 같습니다

2022-06-14 09:57 UTC, SH0123 commented on Taxi/Taxi/Extension/DateExtension.swift
> +        return self.dateComponents.day ?? -1
-> 팀원들과의 협의 뒤에 nil 값을 가져올 경우 view에 어떤 모습으로 띄워줄지 결정한다, 그리고 그에 맞춰 else문의 return 값을 결정한다

2022-06-14 12:38 UTC, SH0123 commented on Taxi/Taxi/Presenter/CalendarView.swift
> +    }
2c72e0bf5ff5309bcc746f1f3fde25834cbaebb6
반영 완료하였습니다 ~ 코드가 좀 더 깔끔해지고 역할에 따라 잘 분리되었습니다. 감사합니다