Feature/#21 taxi party list
DeveloperAcademy-POSTECH/MC2-Team3-SSAK3 pull request #54
Opened 2022-06-12 05:57 UTC by pis3120

## 작업사항
1. CellView 및 TaxiPartyList 합쳐서 기본 UI 세팅

2. Filter (전체, 포항역, 포스텍) 선택하면 아래 검은줄 움직이게 -> Library 씀.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/40324511/173217469-c22d8a72-66b6-4d36-a8f5-f3ee1a7c418a.png">

## 리뷰포인트
1. CellView -> RGB값 넣어서 색상 표현한 코드 ->  .background(Color(red: 248 / 255, green: 248 / 255, blue: 248 / 255, opacity: 1.0))  -> 나중에 Color 등록 된 것으로 바꿀 예정

2. TaxiParty 모델에서 가져와야 할 Codable 고민... 현재 상태는 단순 UI만 세팅 되어져 있음.

3. Filter (전체, 포항역, 포스텍) 선택하면 아래 검은줄 움직이게 ->SegmentedPicker Library 있어서, 사용하였음 -> 시간 남으면 직접 구현해서 Library 쓴 것과 비교 하고 싶은 생각.

### 다음으로 진행될 작업
1. 다른 View들과 Merge 해야 함.

2. Merge완료 후, 버튼 별로 화면 전환 테스트.

5. 채팅방 List 부분에 Jerry가 작업한 날짜별로 표시한 것. 공통 코드로 표현 해야 할 듯.

6. 실제 데이터를 불러들여서 택시파티 생성 후 CellView에 표시해서 보여주기

7. Avo와 "택시파티 정보" View Merge 후,  택시파티에 보여지는 실제 정보를 뿌려주는 coding 작업 협업 필수

8. 아래로 드래그 했을때, 실제로 새로고침 되는 기능 추가하기.

9. Filter (전체, 포항역, 포스텍) 선택하면 선택한 목적지 리스트만 보여주기.

2022-06-12 06:28 UTC, HoJongPARK requested changes
전체적으로 고칠 부분 -> Color 와 텍스트 스타일 고치기
고정 사이즈를 가진 Spacer 사용 자제
고정 사이즈를 가진 frame 사용 자제

2022-06-12 06:28 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/CellView.swift
> +            .frame(width: 339, height: 119)
frame 에 직접적인 수치를 줘서 사이즈를 결정하기 보다는 내부 View 들의 intrinsic size, padding 을 활용해 RoundedRectangle 의 크기를 결정하는게 맞습니다

2022-06-12 06:28 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/CellView.swift
> +                    Spacer().frame(width: 6)
MeetingTimeCell 의 leading padding 을 주는 방식으로 해결하는게 Spacer 를 주는 것보다 맞는 것 같네요

2022-06-12 06:28 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/CellView.swift
> +                    Spacer().frame(width: 130)
이 부분도 마찬가지입니다

2022-06-12 06:28 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/CellView.swift
> +struct CellView: View {
TaxiParty Model 이 이미 정해졌고 사용해도 되는 이상 처음부터 TaxiParty 모델과 연동하는게 나을 것 같네요

2022-06-12 06:28 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/CellView.swift
> +            .foregroundColor(Color(red: 64 / 255, green: 64 / 255, blue: 64 / 255, opacity: 1.0))
색상이나 폰트 스타일도 지금 조이가 추가헀으니까, github cherrypick 으로 해당 커밋만 가져오고, 나중에 머지할 때 interactive rebase 로 가져온 커밋들을 드랍하고 변경사항만 적용할 수 있습니다

2022-06-12 06:28 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/CellView.swift
> +                .foregroundColor(Color(red: 64 / 255, green: 64 / 255, blue: 64 / 255, opacity: 1.0))
Color 를 cherry pick 으로 가져와서 작업해보세요. 모르시면 물어보셔도 됩니다

2022-06-12 06:28 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                .frame(width: 400)
이 부분도 마찬가지로 직접 넓이를 주는건 좋지 않습니다.

2022-06-12 06:28 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                        .padding(-4)
padding 에 음수를 넣은 이유가 뭔가요??

2022-06-12 06:53 UTC, Chaeho-Min requested changes
레이아웃 구성 방식에 변화가 필요해보입니다!

2022-06-12 06:53 UTC, Chaeho-Min commented on Taxi/Taxi/TaxiApp.swift
> +            TaxiPartyListView()
😮 빌드를 위해 바꾼 이 부분은 PR로 날리면 안됩니다!!

2022-06-12 06:53 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CellView.swift
> +            }
Spacer는 차지할 수 있는 최대 크기를 차지하게 하는 용도로 쓰입니다!
따라서 Spacer에는 웬만하면 frame을 적용하지 않습니다.

여기에서 HStack 안에 쓰인 Spacer는 간격을 위해 쓰인 것 같은데, Spacer 대신 padding을 사용하는 것을 권장드립니다.

```suggestion
            VStack(alignment: .leading, spacing: 13) {
                HStack {
                    MeetingTimeCell()
                    Spacer() // 시간과 인원수 사이를 벌어지게 함
                    CurrentUserCell()
                        .padding(EdgeInsets(top: 0, leading: 15, bottom: 10, trailing: 1))
                }
                DestinationCell()
            }
            .padding() // 셀 컨텐츠를 RoundedButton와 마진을 두고 있게 함 -> 위에서 쓰인 Spacer의 간격이 알아서 조정됨
```

2022-06-12 06:53 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CellView.swift
> +            .frame(width: 339, height: 119)
디자인에 있어 셀은 보통 고정된 좌우 마진을 갖게 됩니다. 즉, 기기 화면 크기에 따라 너비가 달라지고, 내부 컨텐츠의 크기에 따라 높이가 달라져야 하죠.
따라서 이렇게 프레임으로 너비와 높이를 고정시켜버리는 것은 좋은 방법이 아닙니다.

이런 셀뷰의 경우 높이는 내부 컨텐츠가 자동으로 차지하게 두고, 너비는 기기 너비를 전부 차지하게 한 후에 .padding으로 고정된 좌우 마진을 갖게 하면 모든 기기에 적합한 셀뷰를 만들 수 있습니다.
그리고 이는 차지할 수 있는 최대 크기를 자동으로 차지하는 Shape, Spacer, .infinity를 잘 활용하면 됩니다.

```swift
extension View {
    func groupedBG(cornerRadius: CGFloat, color: Color) -> some View {
        self
            .frame(maxWidth: .infinity)
            .padding()
            .background {
                RoundedRectangle(cornerRadius: cornerRadius)
                    .foregroundColor(color)
            }
            .padding(.horizontal)
    }
}
```

위 코드는 제가 예전에 모든 기기에 적합한 셀뷰를 만들어주는 수식어를 제작한 것인데 참고하시면 좋을 것 같습니다.

2022-06-12 06:53 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CellView.swift
> +            .font(.custom("Apple SD Gothic Neo", size: 40))
나중에 만들어놓은 익스텐션을 적용할거라 상관없어보이지만, 폰트 이름을 이렇게 하면 적용이 안되지 않나요?
제가 알기로는 "AppleSDGothicNeo-Regular" 이런 식으로 써야 합니다.

2022-06-12 06:53 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CellView.swift
> +            }.frame(minWidth: 90, minHeight: 20, maxHeight: 28, alignment: .center) // ex) 낙원교차로 등의 긴 문장이 와도 frame이 늘어남
여기도 background로 Shape 타입인 RoundedRectangle이 왔으니 RoundedRectangle은 텍스트의 크기에 따라 자동으로 늘어나게 될 것입니다. 따라서 frame을 주지 않고 padding으로 RoundedRectangle과 텍스트 간 마진만 두면 될 것 같네요.

2022-06-12 06:53 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CellView.swift
> +                Spacer().frame(width: 10)
여기도 마진은 padding을 이용해주세요.

2022-06-12 06:53 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CellView.swift
> +                    .frame(width: 13, height: 17)
SF 심볼은 텍스트처럼 접근할 수 있어서, 프레임 말고 폰트 크기를 조정하는 식으로 하면 됩니다.
그렇게 되면 텍스트와 동일한 수치의 크기를 사용할 수 있게 되겠죠.

2022-06-12 06:53 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                .frame(width: 400)
여기에 너비 프레임을 준 이유는 무엇인가요?
이 프레임이 기기 너비를 초과하게 되어 화면이 이상해지는 문제가 발생할 수 있습니다. (아이폰 13미니의 너비는 375)

2022-06-12 06:53 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                )
혹시 이 Rectangle의 역할은 뭔지 설명해주실 수 있나요?

2022-06-12 06:53 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +        }.padding(20)
전체 컨텐츠에 padding을 주는 방식은 이상해보입니다.
여기서 주지 말고 개별 컨텐츠에 padding을 주는게 나아보입니다.

2022-06-12 10:43 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +                    .frame(width: 13, height: 17)
적용 완료하였습니다.

2022-06-12 10:43 UTC, SH0123 commented on Taxi/Taxi/Presenter/CellView.swift
> +            .frame(width: 339, height: 119)
layout 장인 아보는 역시 다르시군요..!
레이아웃 관련해서 고민이 항상 많았는데 감사합니다 ~

2022-06-12 10:45 UTC, SH0123 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                .frame(width: 400)
프레임 사이즈는 웬만하면 지정해주지 말자! 라는것을 배워갑니다 ~

2022-06-12 11:22 UTC, SH0123 reviewed
고생하셨습니다 ~ 첫 코드리뷰 양이 상당해서 힘드시겠지만 다음번엔 적응되실거에요 ㅎㅎ 저도 조금씩 적응되고 있습니다

2022-06-12 11:22 UTC, SH0123 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +}
해당 부분은 어플 내에 여러군데서 사용되는 header라고 생각됩니다.
같은 방식의 header를 사용하는 팀원들끼리 합의를 하여 custom header를 사용할 것인지, navigationbar를 사용할 것인지 정하면 좋을거라 생각됩니다 ~ 
@HoJongPARK @Chaeho-Min @YoonyoungL

2022-06-12 11:22 UTC, SH0123 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +            print("날짜 선택 tapped!")
해당 위치에서는 
```swift
// TODO: 달력 모달 띄우기
```
이와 같은 방법을 통해 나중에 좀 더 잘 알 수 있도록 작성해 주면 좋을 것 같습니다.
예전에 호종이에게 이런 피드백을 받았어서 좋은건 나눠드립니다 ~

2022-06-12 11:51 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +}
나중에 디자인이 픽스되어야 알겠지만, 현재의 디자인 시안을 봤을 때는 커스텀으로 갈 것 같네요.
디자인이 픽스된 후 공통 컴포넌트로 만들면 될 것 같습니다.

2022-06-12 12:04 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                )
택시파티 리스트와 Filtering 부분에 미세하게 회색깔 경계선 하나가 보여지는데 

<img width="494" alt="image" src="https://user-images.githubusercontent.com/40324511/173232208-9423a6b6-1b6c-4577-84c9-bf9916726337.png">

위와 같이 최대한 똑같이 구현하려고 넣은 코드입니다~!

우선 해당 부분 제거하고 더 좋은 방법이 있는지 코드스타일 변경 테스트하고 있습니다~!

2022-06-12 12:06 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                )
저 부분은 내비게이션바의 배경으로 쓰인 Rectangle에 shadow를 줌으로써 구현할 수 있습니다.
실제로 스케치 작업본에서도 이 방식으로 디자인되어 있고요.

그러나 아직 디자인이 픽스된게 아니기 때문에 저 부분을 아직은 구현할 필요가 없어보입니다.

2022-06-12 12:10 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                )
디자인 시안을 코드로 구현할 때 가장 좋은 방법은 디자인 한 방법 그대로 코드로 구현하는 것이라고 생각합니다.

따라서 스케치에서 요소를 눌러봐서 어떤 효과가 적용되어 있는지 한 번 확인하면 좋습니다.
혹은 이를 도와주는 플러그인 중 하나로 제플린을 추천합니다.

2022-06-12 12:22 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                )
ScrollView에 padding과 .border(Color.gray) 를 주어 비슷하게 표현가능할듯합니다~

2022-06-12 12:29 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                        .padding(-4)
CellVeiw 간의 간격을 더 좁히기 위해서 사용하였습니다. 0이상의 숫자가 오면, 기존 디자인 시안보다 넓게 표현이 되서 우선 음수를 지정해서 최대한 똑같이 표현했습니다.

2022-06-12 12:29 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                .frame(width: 400)
수정완료하였습니다~!

2022-06-12 12:30 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            .foregroundColor(Color(red: 64 / 255, green: 64 / 255, blue: 64 / 255, opacity: 1.0))
오 좋은 기능이네요~! 나중에 merge 기다리지 않고 필요한 부분만 커밋으로 가져 올 수 있군요.

2022-06-12 12:31 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +                .foregroundColor(Color(red: 64 / 255, green: 64 / 255, blue: 64 / 255, opacity: 1.0))
제가 혼자 한번 작업해보고, 잘 안되면 6월 13일 월요일날  대면으로 같이 해주실 것을 요청드립니다~!!

2022-06-12 12:32 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            }
참고해서 수정하였습니다~!

2022-06-12 12:33 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CellView.swift
> +                .foregroundColor(Color(red: 64 / 255, green: 64 / 255, blue: 64 / 255, opacity: 1.0))
그는 대면으로 올 수 없습니다...😢

2022-06-12 12:33 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            .frame(width: 339, height: 119)
오 이거 상당한 꿀팁이네요, 궁금했었는데 !!!

2022-06-12 12:42 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            .font(.custom("Apple SD Gothic Neo", size: 40))
여러번 테스트 결과 "Apple SD Gothic Neo"를 사용해도 "AppleSDGothicNeo-Regular"를 사용한 것과 동일하네요.

2022-06-12 12:45 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                .frame(width: 400)
수정완료하였습니다~~!!

2022-06-12 12:46 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +        }.padding(20)
위와 마찬가지로 ScrollView에 padding과 .border(Color.gray) 를 주어 비슷하게 표현가능할듯합니다~! 디테일한 리뷰 감사해요~!

2022-06-12 12:48 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +}
넵 디자인이 완전 픽스되면, 해당 View가 필요한 개발자와 상의해서  공통 컴포넌트로 만들어서 코드 통일성을 유지하면 좋을거 같아요.

2022-06-12 12:49 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +            print("날짜 선택 tapped!")
좋은 주석 처리 방법이네요. 적용 완료했습니다~!

2022-06-12 12:51 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                        .padding(-4)
사실 padding 값에 0을 넣어도 제 기준에서는 디자인이 크게 변경되는거 같지는 않은데, 디자이너와 상의를 해봐야 할거 같습니다!

2022-06-12 12:54 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            .font(.custom("Apple SD Gothic Neo", size: 40))
> 고생하셨습니다 ~ 첫 코드리뷰 양이 상당해서 힘드시겠지만 다음번엔 적응되실거에요 ㅎㅎ 저도 조금씩 적응되고 있습니다

코드 리뷰 보고 코드 refactoring 하는 것도 스타트업에서 업무보는 느낌이라 진짜 재밌네요! 
코드리뷰 꼼꼼히 해주는 팀원들이 있으면, 실력대비 촉박한 개발이 필요할때 도움이 많이 되는거 같아요.

2022-06-12 13:04 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +                .foregroundColor(Color(red: 64 / 255, green: 64 / 255, blue: 64 / 255, opacity: 1.0))
앗 .... My mistake

2022-06-12 13:10 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CellView.swift
> +            .font(.custom("Apple SD Gothic Neo", size: 40))
<img width="848" alt="image" src="https://user-images.githubusercontent.com/75792767/173234786-feb2c88d-8228-4569-81a8-80c21034b7d2.png">

.custom에 잘못된 폰트 이름이 들어가면 아이폰 기본 폰트인 'SF Pro'가 들어가게 됩니다.
그런데 SF Pro의 한글은 AppleSDGothicNeo와 동일하기 때문에 차이를 느끼지 못하셨을 수 있습니다.
자세히 보시면 숫자와 자간이 조금 다른 것을 확인할 수 있습니다.

2022-06-12 13:16 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +        }.padding(20)
ScrollView에 padding 을 지정해 준 이유는, 회색 배경(사진속, mint색) 이 꽉차게 해주기 위해서 ScrollView에 padding을 주었는데 올바른 방법인지 헷갈리네요?
<img width="307" alt="image" src="https://user-images.githubusercontent.com/40324511/173235071-5649ef45-5e5c-43d7-82fe-cc631033f47d.png">

2022-06-12 13:18 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +        }.padding(20)
.padding(.horizontal, 45) 로 지정해서 13 pro Max에서도 꽉 채워지게끔 지정했는데요, 더 좋은 방법 있으면 공유요청드립니다!

2022-06-12 13:26 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            .font(.custom("Apple SD Gothic Neo", size: 40))
아아~~~~!! 한글이 동일하군요

2022-06-12 13:31 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            .font(.custom("Apple SD Gothic Neo", size: 40))
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/40324511/173235661-bf2c9257-f15a-4ca2-b9c9-1ea8ef79939b.png">

2022-06-12 13:32 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            .font(.custom("Apple SD Gothic Neo", size: 40))
<img width="995" alt="image" src="https://user-images.githubusercontent.com/40324511/173235691-022649ad-e554-4180-824d-8e1531bfc94c.png">

2022-06-12 13:33 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            .font(.custom("Apple SD Gothic Neo", size: 40))
> <img alt="image" width="848" src="https://user-images.githubusercontent.com/75792767/173234786-feb2c88d-8228-4569-81a8-80c21034b7d2.png">
> 
> .custom에 잘못된 폰트 이름이 들어가면 아이폰 기본 폰트인 'SF Pro'가 들어가게 됩니다. 그런데 SF Pro의 한글은 AppleSDGothicNeo와 동일하기 때문에 차이를 느끼지 못하셨을 수 있습니다. 자세히 보시면 숫자와 자간이 조금 다른 것을 확인할 수 있습니다. (자간은 잘 모르겠네요)

저기 보심면 AppleSDGothicNeo-Regular여기 부분이 ApplSDGothicNeo-Regular 이렇게 되어 있어서 그런거 같아요!

2022-06-12 13:34 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            .font(.custom("Apple SD Gothic Neo", size: 40))
처음에 테스트 했을때, 컴퓨터가 이상한가 싶었는데, 신기하네요 한글부분은 똑같은거!

2022-06-12 13:47 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CellView.swift
> +            .font(.custom("Apple SD Gothic Neo", size: 40))
아 ㅋㅋㅋ 이런...
쥐구멍 찾습니다

2022-06-12 13:48 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                )
디자인 픽스되면 나중에 Jerry와 함께 Avo님이 알려준 방법으로 적용할지 논의해봐야 겠어요!

2022-06-12 20:49 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            .frame(width: 339, height: 119)
수정 완료하였습니다.

2022-06-12 21:04 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            }.frame(minWidth: 90, minHeight: 20, maxHeight: 28, alignment: .center) // ex) 낙원교차로 등의 긴 문장이 와도 frame이 늘어남
frame제거 및 padding 적용 완료.

2022-06-12 21:06 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +                    Spacer().frame(width: 6)
고정된  Spacer 제거 완료

2022-06-12 21:06 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +                    Spacer().frame(width: 130)
고정된 Spacer 제거 완료

2022-06-12 21:08 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +                Spacer().frame(width: 10)
frame 제거 완료

2022-06-12 21:31 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                        .padding(-4)
해당부분 padding 제거

2022-06-12 22:16 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +        }.padding(20)
CellViewList Struct에서 LazyVStack 사용 후, 해당부분 padding 값 제거 완료,

2022-06-13 01:38 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                        .padding(-4)
LazyVStack(spacing: 16)으로 padding 값 삭제

2022-06-13 08:38 UTC, Chaeho-Min reviewed
점점 코드가 발전하는게 눈에 보입니다! 너무 좋아요 저는 이제 코드 스타일만 조금 다듬으면 될 것 같습니다!

2022-06-13 08:38 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CellView.swift
> +            } .padding(paddingSize)
각자의 스타일 차이인지 모르겠지만 일단 저희 팀의 코드에서 전부 중괄호 다음 줄에 수식어를 쓰기 시작했으니 스타일 통일해주세요~
```suggestion
            }
            .padding(paddingSize)
```

2022-06-13 08:38 UTC, Chaeho-Min commented on Taxi/Taxi/Presenter/CellView.swift
> +        }
인덴트가 맞지 않습니다...!
여기뿐 아니라 아래에 있는 background 코드가 전부 이렇네요 수정 부탁드리겠습니다.

```suggestion
        .background {
            ZStack { // Struct로 만들어서 표현하자
                RoundedRectangle(cornerRadius: 18.0)
                    .fill(Color(.white))
                    .shadow(color: .black.opacity(0.05), radius: 2, x: 0, y: 1)
                RoundedRectangle(cornerRadius: 16)
                    .stroke(Color(red: 240 / 255, green: 240 / 255, blue: 240 / 255, opacity: 1.0), lineWidth: 1.5)
            }
        }
```

2022-06-14 02:11 UTC, HoJongPARK requested changes
접근 지정자를 신경써주세요

2022-06-14 02:11 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/CalendarModal.swift
> +    let endOpacity: Double = 0.8
이 부분은 외부에서 사용하지 않기 때문에 private 을 적용할 수 있습니다. 항상 접근 지정자에 대해 고민해주세요

2022-06-14 02:11 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/CalendarModal.swift
> +            NavigationView {
이 빈 NavigationView 는 무슨 용도인가요?

2022-06-14 02:11 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +    let titles: [String] = ["전체", "포항역", "포스텍"]
항상 접근 지정자에 대해 고민해주세요

2022-06-14 02:11 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +    @State var mypartys: [TaxiParty] = [
private

2022-06-14 02:33 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +struct CellView: View {
TaxiParty와 연동 완료하였습니다.

2022-06-14 02:33 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            } .padding(paddingSize)
좋습니다~!

2022-06-14 02:33 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +        }
수정완료~!

2022-06-14 02:35 UTC, pis3120 commented on Taxi/Taxi/Presenter/CalendarModal.swift
> +            NavigationView {
차후 달력 컴포넌트와 연동 예정이여서, NavigationView하나 넣어 두었습니다. 주석 달아놓았습니다~!

2022-06-14 02:35 UTC, pis3120 commented on Taxi/Taxi/Presenter/CalendarModal.swift
> +    let endOpacity: Double = 0.8
수정 완료.

2022-06-14 02:37 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +    let titles: [String] = ["전체", "포항역", "포스텍"]
private 적용 완료~!

2022-06-14 02:37 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +    @State var mypartys: [TaxiParty] = [
private 적용 완료!

2022-06-14 02:52 UTC, unnnyong commented on Taxi/Taxi.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = org.ssak3.Taxi2;
개인적인 Build를 위한 수정은 되돌리고, commit 하지 않는게 좋을 것 같아요 ~
Conflict의 위험요소가 될 가능성이 커보여요 ⚠️

2022-06-14 02:52 UTC, unnnyong commented on Taxi/Taxi.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = H4DUZUZV8Z;
개인적인 Build를 위한 수정은 되돌리고, commit 하지 않는게 좋을 것 같아요 ~
Conflict의 위험요소가 될 가능성이 커보여요 ⚠️

2022-06-14 02:54 UTC, unnnyong commented on Taxi/Taxi/Presenter/CalendarModal.swift
> +            } // 차후 달력 컴포넌트와 연동 예정
```suggestion
            } // TODO: 차후 달력 컴포넌트와 연동 예정
```

TODO로 되어있으면 다른 팀원도 어느 타이밍에 달력 컴포넌트가 추가되는지 알아보기 쉬울 것 같아용

2022-06-14 02:54 UTC, pis3120 commented on Taxi/Taxi.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = org.ssak3.Taxi2;
네, 감사합니다!!

2022-06-14 02:54 UTC, unnnyong commented on Taxi/Taxi/Presenter/CellView.swift
> +struct CellView: View {
SwiftUI에서는 View 구조체의 이름 끝에 View를 붙이지 않는 스타일으로 이해하고 있어요 ~
팀원들과 View 네이밍 스타일에 대해서 상의된 상태인가요 ?

2022-06-14 02:55 UTC, pis3120 commented on Taxi/Taxi.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = H4DUZUZV8Z;
수정완료하였습니다.

2022-06-14 02:55 UTC, unnnyong commented on Taxi/Taxi/Presenter/CellView.swift
> +    private let paddingSize: CGFloat = 6
body와 data property들 간에 개행이 하나 있으면 구분하기 쉬울 것 같아요 !
```suggestion
    private let paddingSize: CGFloat = 6

```

2022-06-14 02:56 UTC, pis3120 commented on Taxi/Taxi/Presenter/CalendarModal.swift
> +            } // 차후 달력 컴포넌트와 연동 예정
오, 생각지 못했는데 알려주셔서 감사합니다. 반영 완료하였습니다~!!

2022-06-14 02:56 UTC, unnnyong commented on Taxi/Taxi/Presenter/CellView.swift
> +    let party: TaxiParty
```suggestion
    private let party: TaxiParty
```

2022-06-14 02:56 UTC, unnnyong commented on Taxi/Taxi/Presenter/CellView.swift
> +    func meetTimeSeparator(str1: String) -> String {
property -> method 순으로 struct 내에서의 작성 순서를 추천드립니당 : )

2022-06-14 02:57 UTC, unnnyong commented on Taxi/Taxi/Presenter/CellView.swift
> +    func meetTimeSeparator(str1: String) -> String {
parmeter 의 이름은 str1에서 다른 이름으로의 고민이 필요해보입니다.

2022-06-14 02:58 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +    private let paddingSize: CGFloat = 6
네, 다른부분들도 반영 완료하였습니다.

2022-06-14 02:58 UTC, unnnyong commented on Taxi/Taxi/Presenter/CellView.swift
> +        let index1 = meet.index(meet.endIndex, offsetBy: -2)
offset에 의한 out of range가 발생할 우려는 없을까요 ?
out of range가 발생하면 크래시가 발생되기 때문에, if 문등 등으로 체크하면 안전하게 구현될 수 있지않을까 싶어요

2022-06-14 02:59 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +        let index1 = meet.index(meet.endIndex, offsetBy: -2)
맞습니다. 저도 생각했던 부분인데, 저 offset이 조금이라도 달라지면 앱이 Crash 나는걸 어제 확인했습니다. if문으로 안전하게 처리 하겠습니다.

2022-06-14 02:59 UTC, HoJongPARK commented on Taxi/Taxi/Presenter/CellView.swift
> +struct CellView: View {
그 부분은 아직 상의 못했습니다. 네이밍 컨벤션에 대해서 짚고 가야할 필요성을 느끼네요 ㅠㅠ

2022-06-14 03:00 UTC, unnnyong commented on Taxi/Taxi/Presenter/CellView.swift
> +        Text("\(meetTimeSeparator(str1: String(party.meetingTime)))")
party property 에서 meetingTime만 사용되는 것 같네요,
`party`를 meetingTime으로 변경해서, 해당값만 init parameter로 받으면 어떤가요 ?

2022-06-14 03:00 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +    let party: TaxiParty
수정 완료하였습니다~!

2022-06-14 03:01 UTC, HoJongPARK commented on Taxi/Taxi.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = org.ssak3.Taxi2;
저 부분은 실제 기기에 빌드하기 위해서 바꾼 것 같아서 비비의 세션과 관련된 내용인 것 같은데 제가 코로나라서 듣지를 못했네요 ㅠㅠ 들으신 팀원분들 공유바랍니다

2022-06-14 03:02 UTC, unnnyong commented
PR 본문을 자세하게 작성해주시고, 스크린샷까지 첨부해주셔서 어느 화면의 작업인지 파악하기 쉬워서, 리뷰하기가 너무 좋았어요 : ) !!
다음엔 타이틀도 예쁘게 작성 부탁드려요 😻

2022-06-14 03:02 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +struct CellView: View {
네 팀원들과는 암묵적으로 상의하여서 사용하였는데, 나중에는 View구조체 이름에는 View를 붙이지 않아야 겠네요!!

2022-06-14 03:05 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +    let party: TaxiParty
` HStack {
                MeetTimeView(party: party)
                Spacer()
                HStack(spacing: 4) {`

2022-06-14 03:07 UTC, Chaeho-Min commented on Taxi/Taxi.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = org.ssak3.Taxi2;
들으신 팀원분 공유바랍니다 @SH0123

2022-06-14 03:09 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +    let party: TaxiParty
해당부분 수정후, 위의 CellView struct Body에서  MeetTimeView(party: party)부분에서 error가 나서 우선, undo 하였습니다!

2022-06-14 03:10 UTC, pis3120 commented
> PR 본문을 자세하게 작성해주시고, 스크린샷까지 첨부해주셔서 어느 화면의 작업인지 파악하기 쉬워서, 리뷰하기가 너무 좋았어요 : ) !! 다음엔 타이틀도 예쁘게 작성 부탁드려요 😻



> PR 본문을 자세하게 작성해주시고, 스크린샷까지 첨부해주셔서 어느 화면의 작업인지 파악하기 쉬워서, 리뷰하기가 너무 좋았어요 : ) !! 다음엔 타이틀도 예쁘게 작성 부탁드려요 😻

바쁘실텐데, 제가 알고 싶었던 부분들 꼼꼼히 잘 알려주셔서 정말 정말 감사합니다!! ㅠㅠㅠㅠ

2022-06-14 03:12 UTC, unnnyong commented on Taxi/Taxi/Presenter/CellView.swift
> +            }
```suggestion
                CurrentPartyMembersView()
```

별도의 struct 혹은 @viewBuilder method 로 정의해서 body를 줄여보는건 어떨까요 ?
각각의 HStack 혹은 VStack이 정리되면, 아래처럼 body의 코드가 심플해지고 특정 영역의 수정이 필요할 때 찾기도 쉽답니다

```swift
VStack {
    HStack {
        MeetTimeView(party: party)
        CurrentPartyMembersView()
    }
    DefatureAndArrivalAreaView()
}

```

2022-06-14 03:13 UTC, unnnyong commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +import SegmentedPicker
```suggestion
import SegmentedPicker
import SwiftUI
```

알파벳순이 좋답니다 ~ ✨

2022-06-14 03:14 UTC, unnnyong commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +    }
Task의 extension method 로 옮기면 어떨까요 ?
method이름의 something이 애매해보여서 이름이 조금 더 명확하게 되어야 할 것 같아욥

2022-06-14 03:15 UTC, unnnyong commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +            // .font(.system(size: 26))
주석은 앞으로도 필요한 코드일까요 ? 아니면 삭제되면 좋을 것 같아요 : )

2022-06-14 03:15 UTC, unnnyong commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                .font(.custom("Apple SD Gothic Neo", size: 26))
해당 폰트를 사용하는 곳이 많아보여요 ~
Font 의 custom method로 추가하면 어때요 ?

2022-06-14 03:16 UTC, unnnyong commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +            MyProgress()    // ProgressView() ?? - no, it's boring :)
나중에 수정될 예정인가요 ?? 👀

2022-06-14 03:17 UTC, unnnyong commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +struct ViewOffsetKey: PreferenceKey {
별도의 swift 파일에서 정의하면 어떨까합니다 ~

2022-06-14 03:17 UTC, unnnyong commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +            if $0 < -270 && !isRefreshing {   // << any criteria we want !!
-270 은 어떤 의미인가요 ? 👀

2022-06-14 03:21 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +            if $0 < -270 && !isRefreshing {   // << any criteria we want !!
스크롤 뷰를 위에서 아래로 잡아댕기는 제스처 할때, criteria 값입니다! 만약 -300을 주면 살짝 더 잡아서 내려야 합니다!

2022-06-14 03:23 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +                .font(.custom("Apple SD Gothic Neo", size: 26))
네 감사합니다! 이번 PR 마무리하고, develop과 merge후에 Font 및 Color custom method로 적용예정입니다.

2022-06-14 03:23 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +            // .font(.system(size: 26))
네, 주석은 필요한 정보만 달아두겠습니다. 수정완료하였습니다.

2022-06-14 03:24 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +import SegmentedPicker
오 처음 아는 꿀팁이네요! 수정완료하였습니다.

2022-06-14 03:26 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            }
네 이전에, 사실 위와 같이 Struct 형식으로 코딩을 했었는데, party: party부분을 나머지 Struct에 명시하는 과정중에 error가 나서 다시한번 코드 refactoring해서 수정 시도해보겠습니다.

2022-06-14 03:27 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +            MyProgress()    // ProgressView() ?? - no, it's boring :)
해당 주석부분 참고용으로 놓아두었는데, 삭제하였습니다.

2022-06-14 03:30 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +    func meetTimeSeparator(str1: String) -> String {
네, 파라미터 이름, meetTime 으로 수정하였습니다.

2022-06-14 03:32 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +    func meetTimeSeparator(str1: String) -> String {
말씀해주신 property -> method 순으로 순서 배치 완료하였습니다.

2022-06-14 03:33 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +        let index1 = meet.index(meet.endIndex, offsetBy: -2)
현재는 TODO: 주석처리하여서 잊지안고 안전하게 구현하도록 하겠습니다.

2022-06-14 03:56 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +        Text("\(meetTimeSeparator(str1: String(party.meetingTime)))")
감사합니다! 수정완료하였습니다!

2022-06-14 07:04 UTC, pis3120 commented on Taxi/Taxi/Presenter/TaxiPartyListView.swift
> +            if $0 < -270 && !isRefreshing {   // << any criteria we want !!
오...넵!! 반영하였습니다~!!

2022-06-14 08:34 UTC, Chaeho-Min approved these changes
정말 수고하셨습니다. 이번 코드 리뷰를 통해 엄청 많은 공부를 하셨을 것 같아요 👍👍

2022-06-14 08:46 UTC, pis3120 commented on Taxi/Taxi/Presenter/CellView.swift
> +            }
refactoring 완료하였습니다.

2022-06-14 11:18 UTC, HoJongPARK approved these changes

2022-06-14 18:55 UTC, merged